"""Import every ORM model into one discoverable namespace.

Importing a declarative model registers its table with ``Base.metadata``.
Alembic imports this package before comparing metadata to PostgreSQL, so a
model omitted here could exist in application code but be invisible to
autogenerated migrations. ``__all__`` also documents the supported model
surface for ``from app.models import ...`` callers.
"""

from app.models.audit_log import AuditLog
from app.models.enums import ManualAction, UserRole
from app.models.login_attempt import LoginAttempt
from app.models.manual import Manual
from app.models.manual_access_log import ManualAccessLog
from app.models.manual_annotation import ManualAnnotation
from app.models.manual_category import ManualCategory
from app.models.manual_reads import ManualRead
from app.models.manual_update_event import ManualUpdateEvent
from app.models.manual_update_read import ManualUpdateRead
from app.models.message import Message
from app.models.message_attachment import MessageAttachment
from app.models.org import Org
from app.models.session import Session
from app.models.user import User
from app.models.user_profile_picture import UserProfilePicture

__all__ = [
    "AuditLog",
    "LoginAttempt",
    "Manual",
    "ManualAccessLog",
    "ManualAction",
    "ManualAnnotation",
    "ManualCategory",
    "ManualRead",
    "ManualUpdateEvent",
    "ManualUpdateRead",
    "Message",
    "MessageAttachment",
    "Org",
    "Session",
    "User",
    "UserProfilePicture",
    "UserRole",
]
